language: node_js
node_js:
  - lts/*
cache: npm install
addons:
  sonarqube: true
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test-coverage
        - ./scripts/integration-headless.sh
stages:
  - test
